Legal_Consultation_hub/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('search_lawyer/', include('search_lawyer.urls')),
    path('', include('home.urls')),
    path('consultation_packages/', include('consultation_packages.urls')),
    path('law_library/', include('law_library.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('payments/', include('payments.urls')),
    path('reviews/', include('review.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'Legal_Consultation_hub.views.handler404'

home/urls.py
from django.contrib import admin
from django.urls import path
from .import views


urlpatterns = [   
     path('', views.home_page, name='home_page'),
]

payments/urls.py
from django.urls import path
from . import views


app_name = 'payments'

urlpatterns = [
    path('checkout/<int:package_id>/', views.checkout, name='checkout'),
    path('success/<int:payment_id>/', views.payment_success, name='success'),
    path('history/', views.payment_history, name='history'),
    path('delete/<int:payment_id>/', views.payment_delete, name='payment_delete'),
    path('subscription_checkout/<int:payment_id>/', views.subscription_checkout, name='subscription_checkout'),
    path('webhook/', views.stripe_webhook, name='stripe_webhook'),

]

review/urls.py
from django.urls import path
from . import views


app_name = 'reviews'


urlpatterns = [
path('package/<int:package_id>/add/', views.add_package_review, name='package_add'),
path('load-more-package-reviews/', views.load_more_package_reviews, name='load_more_package_reviews'),
]

subscriptions/urls.py
from django.urls import path
from . import views

app_name = 'subscriptions'

urlpatterns = [
    path('', views.subscription_list, name='list'),
    path('checkout/<str:plan>/', views.subscription_checkout, name='checkout'),
    path('renew/<str:plan>/', views.renew_subscription, name='renew'),
    path('my_subscription/', views.my_subscription, name='my_subscription'),

]

payments/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from decimal import Decimal
from subscriptions.models import Subscription
from consultation_packages.models import ConsultationPackage


class Payment(models.Model):
    PAYMENT_METHODS = [
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        ('stripe', 'Stripe'),
    ]

    PENDING = 'pending'
    COMPLETED = 'completed'
    FAILED = 'failed'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (COMPLETED, 'Completed'),
        (FAILED, 'Failed'),
    ]
    CONSULTATION_PACKAGE = 'consultation_package'
    SUBSCRIPTION = 'subscription'

    PAYMENT_TYPE_CHOICES = [
        (CONSULTATION_PACKAGE, 'Consultation_Package'),
        (SUBSCRIPTION, 'Subscription'),
    ]

    payment_type = models.CharField(
        max_length=20,
        choices=PAYMENT_TYPE_CHOICES,
        null=True, blank=True

    )

    subscription_plan = models.CharField(
        max_length=10,
        null=True, blank=True
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )

    package = models.ForeignKey(
        'consultation_packages.ConsultationPackage',
        on_delete=models.CASCADE, null=True, blank=True
    )

    stripe_session_id = models.CharField(max_length=255, blank=True, null=True)

    method = models.CharField(max_length=20, choices=PAYMENT_METHODS)

    full_name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    address = models.TextField(null=True, blank=True)

    original_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )

    discount_percent = models.PositiveIntegerField(default=0)

    final_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )

    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=PENDING
    )

    created_at = models.DateTimeField(auto_now_add=True)
    paid_at = models.DateTimeField(null=True, blank=True)

    def apply_subscription_discount(self):
        """
        Apply discount based on user's active subscription.
        """
        percent = 0

        subscription = Subscription.objects.filter(
            user=self.user,
            expires_at__gt=timezone.now()
        ).first()

        if subscription:
            percent = subscription.discount_percent()

        discount = (self.original_amount * Decimal(percent)) / Decimal(100)
        self.discount_percent = percent
        self.final_amount = self.original_amount - discount
        self.save(update_fields=[
            'discount_percent',
            'final_amount'
        ])

    def mark_completed(self):
        self.status = self.COMPLETED
        self.paid_at = timezone.now()
        self.save(update_fields=['status', 'paid_at'])

    def __str__(self):
        return f"Payment #{self.id} - {self.user} - {self.status}"

payments/forms.py
from django import forms


class CheckoutForm(forms.Form):
    full_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField(max_length=20)
    address = forms.CharField(widget=forms.Textarea)

    widgets = {
        'full_name': forms.TextInput(attrs={'class': 'form-control'}),
        'email': forms.EmailInput(attrs={'class': 'form-control'}),
        'phone': forms.TextInput(attrs={'class': 'form-control'}),
        'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 2}),
        'cardholder_name': forms.TextInput(attrs={'class': 'form-control'}),
        'card_number': forms.TextInput(attrs={'class': 'form-control'}),
        'expiry_month': forms.Select(attrs={'class': 'form-control'}),
        'expiry_year': forms.Select(attrs={'class': 'form-control'}),
        'cvv': forms.PasswordInput(attrs={'class': 'form-control'}),
        
    }

payments/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from urllib3 import request
from consultation_packages.models import ConsultationPackage
from subscriptions.models import Subscription
from .models import Payment
from django.contrib import messages
from datetime import timedelta
from django.utils import timezone
from .forms import CheckoutForm
import stripe
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.utils.timezone import now


@login_required
def checkout(request, package_id):
    package = get_object_or_404(ConsultationPackage, id=package_id)

    subscription = Subscription.objects.filter(user=request.user).first()
    discount = subscription.discount_percentage() if subscription else 0

    # Decide original amount
    original_amount = (
        package.min_price if package.min_price else package.max_price
    )

    # Apply discount
    final_amount = original_amount - (original_amount * discount / 100)

    if request.method == 'POST':
        form = CheckoutForm(request.POST)

        if form.is_valid():

            payment = Payment.objects.create(
                user=request.user,
                package=package,

                full_name=form.cleaned_data['full_name'],
                email=form.cleaned_data['email'],
                phone=form.cleaned_data['phone'],
                address=form.cleaned_data['address'],
                original_amount=original_amount,
                discount_percent=discount,
                final_amount=final_amount,
            )
            stripe.api_key = settings.STRIPE_API_KEY

            session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                mode='payment',
                customer_email=payment.email,
                line_items=[{
                    'price_data': {
                        'currency': 'gbp',
                        'product_data': {
                            'name': package.title,
                        },
                        'unit_amount': int(final_amount * 100),
                    },
                    'quantity': 1,
                }],

                success_url=request.build_absolute_uri(
                    reverse('payments:success', args=[payment.id])
                ),

                cancel_url=request.build_absolute_uri(
                    reverse('payments:checkout', args=[package.id])
                ),
            )

            payment.stripe_session_id = session.id
            payment.save()

            return redirect(session.url)

    else:
        form = CheckoutForm(
            initial={
                'email': request.user.email
            }
        )

    # ✅ THIS MUST ALWAYS RUN
    context = {
        'package': package,
        'original_amount': original_amount,
        'discount': discount,
        'final_amount': final_amount,
        'subscription': subscription,
        'form': form,
        'STRIPE_PUBLISHABLE_KEY': settings.STRIPE_PUBLISHABLE_KEY
    }

    return render(request, 'payments/checkout.html', context)


@login_required
def payment_success(request, payment_id):
    payment = get_object_or_404(Payment, id=payment_id, user=request.user)
    stripe.api_key = settings.STRIPE_API_KEY
    session = stripe.checkout.Session.retrieve(payment.stripe_session_id)

    if session.payment_status == 'paid':
        payment.mark_completed()


        # updat subscription

        if payment.payment_type == Payment.SUBSCRIPTION:
            subscription, _ = Subscription.objects.get_or_create(
                user=request.user
            )

            subscription.plan = payment.subscription_plan
            subscription.started_at = timezone.now()

            if payment.subscription_plan == 'basic':
                subscription.expires_at = timezone.now() + timedelta(days=90)
            elif payment.subscription_plan == 'full':
                subscription.expires_at = timezone.now() + timedelta(days=90)

            subscription.save()

    return render(request, 'payments/payment_success.html', {'payment': payment})


@csrf_exempt
def stripe_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except Exception:
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        payment = Payment.objects.filter(stripe_session_id=session.id).first()
        if payment:
            payment.mark_completed()

    return HttpResponse(status=200)


@login_required
def payment_history(request):
    payments = Payment.objects.filter(
        user=request.user).order_by('-created_at')
    return render(request, 'payments/payment_history.html', {'payments': payments})


@login_required
def payment_delete(request, payment_id):
    # Try to get the payment for this user
    payment = Payment.objects.filter(id=payment_id, user=request.user).first()

    if not payment:
        messages.error(request, "Payment not found or you cannot delete it.")
        return redirect('payments:history')  # redirect to payment history

    if request.method == 'POST':
        payment.delete()
        messages.success(request, "Payment deleted successfully.")
        return redirect('payments:history')

    # Optional: render confirmation page
    return redirect('payments:history')


@login_required
def subscription_checkout(request, payment_id):
    payment = get_object_or_404(Payment, id=payment_id, user=request.user)

    if request.method == 'POST':

        stripe.api_key = settings.STRIPE_API_KEY

        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            mode='payment',

            line_items=[{
                'price_data': {
                    'currency': 'gbp',
                    'product_data': {
                        'name': f"{payment.subscription_plan.capitalize()} Subscription",
                    },
                    'unit_amount': int(payment.final_amount * 100),
                },
                'quantity': 1,
            }],
            success_url=request.build_absolute_uri(
                reverse('payments:success', args=[payment.id])
            ),
            cancel_url=request.build_absolute_uri(
                reverse('subscriptions:list')
            ),
        )

        payment.stripe_session_id = session.id
        payment.save()

        return redirect(session.url)

    else:
        context = {
            'payment_id': payment_id,
            'STRIPE_PUBLISHABLE_KEY': settings.STRIPE_PUBLISHABLE_KEY,
            'payment': payment,
            'final_amount': payment.final_amount,
        }

        return render(request, 'payments/subscription_checkout.html', context)


@login_required
def subscription_success(request, payment_id):
    payment = get_object_or_404(Payment, id=payment_id, user=request.user)

    stripe.api_key = settings.STRIPE_API_KEY
    session = stripe.checkout.Session.retrieve(payment.stripe_session_id)

    if session.payment_status == 'paid':
        payment.mark_completed()

        subscription, _ = Subscription.objects.get_or_create(
            user=request.user
        )

        subscription.activate(payment.subscription_plan)
        subscription.refresh_from_db()

    return redirect('subscriptions:my_subscription')

payments/templates/payments/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Checkout{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'payments/css/pay_checkout.css' %}">
    
{% endblock %}

{% block content %}
<div class="container my-5">
    <h2 class="mb-4 checkout-title">Checkout</h2>

    <form method="post">
        {% csrf_token %}

        <div class="row g-4">

            <!-- LEFT: CUSTOMER & CARD DETAILS -->
            <div class="col-lg-7">
                <div class="card p-4">

                    <h5 class="mb-4">Customer Details</h5>

                    <div class="mb-3">
                        <label class="col-sm-2 form-label">{{ form.full_name.label_tag }}</label>
                        {{ form.full_name }}
                    </div>

                    <div class="mb-3">
                        <label class="col-sm-2 form-label">{{ form.email.label_tag }}</label>
                        {{ form.email }}
                    </div>

                    <div class="mb-3">
                        <label class="col-sm-2 form-label">{{ form.phone.label_tag }}</label>
                        {{ form.phone }}
                    </div>

                    <div class="mb-4">
                        <label class="form-label">{{ form.address.label_tag }}</label>
                        {{ form.address }}
                    </div>
                    <div class="alert alert-info mt-3">
                        🔒 Payment details will be securely entered on Stripe.
                        <br>
                        We never store your card information.
                    </div>
                    
                    </div>
                </div>
            

            <!-- RIGHT: ORDER SUMMARY -->
            <div class="col-lg-5">
                <div class="card p-4">

                    <h5 class="mb-2">{{ package.title }}</h5>
                    <p class="text-muted">{{ package.description }}</p>

                    <hr>

                    <div class="d-flex justify-content-between mb-2">
                        <span>Original Price</span>
                        <strong>£{{ original_amount }}</strong>
                    </div>

                    <div class="d-flex justify-content-between mb-3">
                        <span>Subscription Discount</span>
                        <strong>{{ discount }}%</strong>
                    </div>

                    <div class="d-flex justify-content-between mb-4">
                        <span class="summary-price">Final Price</span>
                        <span class="summary-price">£{{ final_amount }}</span>
                    </div>

                    <button type="submit" class="btn btn-success btn-lg w-100">
                        Confirm & Pay with Stripe
                    </button>
                </div>
            </div>
        </div>
        </div>
    </form>

    {% if form.errors %}
    <div class="alert alert-danger mt-4">
        {{ form.errors }}
    </div>
    {% endif %}
</div>
{% endblock %}

payments/templates/payments/payment_history.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Payment History{% endblock %}


{% block extra_css %}
    <link rel="stylesheet" href="{% static 'payments/css/pay_history.css' %}">
    
{% endblock %}


{% block content %}
<h1 class="mb-4">Payment History</h1>

<div class="table-responsive mb-4 shadow-sm bg-white rounded">
<table class="table table-bordered">
<thead>
<tr>
<th>Package</th>
<th>Original</th>
<th>Discount</th>
<th>Final</th>
<th>Status</th>
<th>Date</th>
<th>Actions</th>
</tr>
</thead>

<tbody>
{% for payment in payments %}
<tr>
    <td>{{ payment.package.title }}</td>
    <td>£{{ payment.original_amount }}</td>
    <td>{{ payment.discount_percent }}%</td>
    <td>£{{ payment.final_amount }}</td>
    <td>{{ payment.get_status_display }}</td>
    <td>{{ payment.created_at|date:"Y-m-d" }}</td>

    <td>
        <form method="post" action="{% url 'payments:payment_delete' payment.id %}">
            {% csrf_token %}
            <button type="submit"
                    class="btn btn-danger btn-sm"
                    onclick="return confirm('Are you sure you want to delete this payment?');">
                Delete
            </button>
        </form>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="7" class="text-center">No payments yet.</td>
</tr>
{% endfor %}
</tbody>

</table>
</div>

<div class="text-center">
<a href="{% url 'home_page' %}" class="btn btn-primary mt-3">Back to main page</a>
</div>
{% endblock %}

payments/templates/payments/payment_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Payment Successful{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'payments/css/pay_success.css' %}">
    
{% endblock %}


{% block content %}
<div class="alert alert-success">
    <h3>Payment Successful</h3>

    {% if payment.payment_type != 'subscription' %}
        <p>
            Thank you {{ payment.full_name }} for your payment.
            A confirmation email will be sent to {{ payment.email }}.
        </p>
        <p>
            Your consultation package with
            <strong>{{ payment.package.lawyer.name }}</strong>
            is now active.
        </p>
    {% endif %}

    {% if payment.payment_type == 'subscription' %}
        <p>
            Your subscription plan
            <strong>{{ payment.subscription_plan|capfirst }}</strong>
            is now active.
        </p>
    {% endif %}
</div>

<div class="card p-4">
    {% if payment.payment_type == 'subscription' %}
        <p>
            <strong>Subscription Plan:</strong>
            {{ payment.subscription_plan|capfirst }}
        </p>

    {% elif payment.payment_type != 'subscription' %}
        <p>
            <strong>Package:</strong>
            {{ payment.package.title }}
        </p>
        <p>
            <strong>Lawyer:</strong>
            {{ payment.package.lawyer.name }}
        </p>
    {% endif %}

    <p><strong>Amount Paid:</strong> £{{ payment.final_amount }}</p>
    <p><strong>Status:</strong> {{ payment.get_status_display }}</p>
</div>

<div class="mt-3">
    <a href="{% url 'package_list' %}" class="btn btn-primary">
        Back to Packages
    </a>

    <a href="{% url 'payments:history' %}" class="btn btn-outline-dark">
        Payment History
    </a>

    {% if payment.payment_type != 'subscription' %}
        <a href="{% url 'reviews:package_add' payment.package.id %}"
           class="btn btn-success">
            Leave a Review
        </a>
    {% endif %}
</div>
{% endblock %}

payments/templates/payments/subscription_checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Subscription Checkout{% endblock %}


{% block extra_css %}
    <link rel="stylesheet" href="{% static 'payments/css/subs_checkout.css' %}">
    
{% endblock %}


{% block content %}
<h2>Subscription Checkout</h2>


<div class="card p-4">
    <p><strong>Amount:</strong> £{{ payment.final_amount }}</p>
    
    <div class="col-md-6">
            <p><strong>Duration:</strong> 3 months</p>
        </div>


        
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-success btn-lg">Confirm & Pay</button>
    </form>

    
        <a href="{% url 'subscriptions:list' %}" class="btn btn-secondary btn-lg mt-3">Back</a>
    </div>

</div>
{% endblock %}