Legal_Consultation_hub/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('search_lawyer/', include('search_lawyer.urls')),
    path('', include('home.urls')),
    path('consultation_packages/', include('consultation_packages.urls')),
    path('law_library/', include('law_library.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('payments/', include('payments.urls')),
    path('reviews/', include('review.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'Legal_Consultation_hub.views.handler404'

home/urls.py
from django.contrib import admin
from django.urls import path
from .import views


urlpatterns = [   
     path('', views.home_page, name='home_page'),
]

subscriptions/urls.py
from django.urls import path
from . import views

app_name = 'subscriptions'

urlpatterns = [
    path('', views.subscription_list, name='list'),
    path('checkout/<str:plan>/', views.subscription_checkout, name='checkout'),
    path('renew/<str:plan>/', views.renew_subscription, name='renew'),
    path('my_subscription/', views.my_subscription, name='my_subscription'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
        content="Connect with expert lawyers, explore legal packages, and access a comprehensive law library.">
    <meta name="keywords" content="Legal Consultation, Find Lawyer, Law Packages, Law Library, Legal Advice, Good Lawyers, Affordable Lawyers, 
    Solicitors in Yorkshire, Advocates, Legal Services, Online Legal Help, Legal Documents, Court Representation, Wills and Deeds,
    Business Contracts, Family Law, Criminal Defence, Legal Resources, Legal Support, Legal Guidance, Legal Consultation Hub,child custody, divorce, 
    top-rated lawyers, legal representation, legal documents, legal advice, legal platform, free law library, affordable legal services, trusted lawyers, 
    legal assistance, legal consultation online, legal expertise, legal solutions, legal professionals, baristors, baristors near me, 
    solicitors near me, legal aid, legal consultation services, i need a solicitor, hire a lawyer, i need a criminal lawyer, best solicitors in yorkshire,
    magistrates court lawyer, high court baristors, free legal advice">
    {% endblock %}
 

    {% block corecss %}
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&display=swap">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        crossorigin="anonymous"
        />

    {% endblock %}

    {% block extra_css %}

    {% endblock %}

     {% block corejs %}
    <!-- Bootstrap 5 JS bundle -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/4c5a23c7c3.js" crossorigin="anonymous"></script>
    <!-- Stripe -->
     <script src="https://js.stripe.com/v3/"></script>
    {% endblock %}

    {% block extra_js %}
    {% endblock %}
</head>

<body>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container">
            <a class="navbar-brand  fw-bold" href="/">
                <span class="d-inline d-lg-inline">Legal Consultation Hub</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto gap-2 gap-lg-0">
                    <li class="nav-item"><a href="{% url 'search_lawyer' %}" class="nav-link fs-6 fs-lg-4 ">Find Lawyer</a></li>
                    <li class="nav-item"><a href="{% url 'package_list' %}" class="nav-link fs-6 fs-lg-4 ">Packages</a></li>
                    <li class="nav-item"><a href="{% url 'book_list' %}" class="nav-link fs-6 fs-lg-4 ">Law Library</a></li>
                    <li class="nav-item"><a href="{% url 'subscriptions:list' %}" class="nav-link fs-6 fs-lg-4 ">Subscriptions</a></li>
                    <li class="nav-item"><a class="nav-link fs-6 fs-lg-4 " href="{% url 'subscriptions:my_subscription' %}">My Subscription</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a href="/accounts/logout/" class="nav-link fs-6 fs-lg-4 ">Logout</a></li>
                    {% else %}
                        <li class="nav-item"><a href="/accounts/login/" class="nav-link fs-6 fs-lg-4">Login</a></li>
                        <li class="nav-item"><a href="/accounts/signup/" class="nav-link fs-6 fs-lg-4">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block page_header %}{% endblock %}
    <!-- Main content -->
    <main class="container px-3 px-lg-0">
        {% block content %}{% endblock %}
    </main>

    <!-- Footer -->

    <footer class="bg-dark text-light py-4 mt-5">
        <div class="container text-center">
            <p>Follow us on:</p>

            {% if settings.facebook %}<a href="{{ settings.facebook }}" target="_blank" rel="noopener" class="text-light"><i class="fab fa-facebook fa-lg mx-2"></i></a>{% endif %}
            {% if settings.twitter %}<a href="{{ settings.twitter }}" target="_blank" rel="noopener" class="text-light"><i class="fab fa-twitter fa-lg mx-2"></i></a>{% endif %}
            {% if settings.linkedin %}<a href="{{ settings.linkedin }}" target="_blank" rel="noopener" class="text-light"><i class="fab fa-linkedin fa-lg mx-2"></i></a>{% endif %}
            {% if settings.instagram %}<a href="{{ settings.instagram }}" target="_blank" rel="noopener" class="text-light"><i class="fab fa-instagram fa-lg mx-2"></i></a>{% endif %}
            {% if settings.youtube %}<a href="{{ settings.youtube }}" target="_blank" rel="noopener" class="text-light"><i class="fab fa-youtube fa-lg mx-2"></i></a>{% endif %}
           
            <p class="m-0">© 2025 LegalHub — All rights reserved.</p>

        </div>
    </footer>

      {% block postloadjs %}
      
      {% endblock %}
   


</body>

</html>